Feat: products screen
nicolasgandrade/fp3 pull request #11
Opened 2023-04-08 21:02 UTC by ViniciusKalach

Create products screen + products edit and create modal

2023-04-08 23:52 UTC, nicolasgandrade commented
Open the PR again but with develop branch as the destination

2023-04-08 23:58 UTC, ViniciusKalach commented
I edited the pull-request and switched from master to develop

2023-04-09 00:09 UTC, nicolasgandrade requested changes
Fine for me. Just make those changes I commented so I can approve.
Good job.

2023-04-09 00:09 UTC, nicolasgandrade commented on src/main/java/com/fp3/haras/view/screens/products/ProductsScreen.java
> +
You can remove this empty line

2023-04-09 00:09 UTC, nicolasgandrade commented on src/main/java/com/fp3/haras/view/screens/products/ProductsScreen.java
> +
This one too

2023-04-09 01:26 UTC, ViniciusKalach commented
I erased the lines, changes met

2023-04-10 22:19 UTC, merged